name = "jiwonz/roblox_install"
version = "0.1.0"
description = "Get the install directory of Roblox in Lune"
authors = ["jiwonz"]
repository = "https://github.com/jiwonz/roblox-install-lune"
license = "MPL-2.0"
includes = ["LICENSE.md", "pesde.toml", "README.md", "src"]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.1.0" }
winreg = { name = "jiwonz/winreg", version = "^0.1.0" }
dirs = { name = "jiwonz/dirs", version = "^0.1.0" }
